### ISSUE TITLE
ProviderReference for a managed resource should be optional

### ISSUE THREAD

**Issue by soorena776** [crossplane/crossplane-runtime#101]
### What problem are you facing?

The `ProviderReference` is currently a _required_ field in both [managed resource](https://github.com/crossplaneio/crossplane-runtime/blob/48b0b781e7080dd17f7b8a596118991425405ac4/apis/core/v1alpha1/resource.go#L151), and [class template](https://github.com/crossplaneio/crossplane-runtime/blob/48b0b781e7080dd17f7b8a596118991425405ac4/apis/core/v1alpha1/resource.go#L186) definitions. However, this has two issues:

- Since this field is never consumed in the runtime library, it's not clear whether this should a required field. 
- If a resource is using another mechanism for connecting to the provider (Vault token, local Kubernetes resource, GCP auth, etc...), it will need to put a dummy value for this field, even though it never gets used.

### How could Crossplane help solve your problem?

Make this field _optional.

**Comment by negz** [comment]
I think this field should always be required. Our emergent pattern for alternative configuration methods (i.e. service account based auth) is for the provider to configure that.
