### ISSUE TITLE
Add EquateParameters cmp helper

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane-runtime#114]
### What problem are you facing?

https://github.com/crossplaneio/stack-gcp/pull/151/files?file-filters%5B%5D=.go#diff-888e0ec46a21ebd2bbdc8d86d4553d9bR92

```go
	return cmp.Equal(in, currentParams, cmpopts.IgnoreInterfaces(struct{ resource.AttributeReferencer }{}))
```

We frequently use the above `cmpopt` when determining whether managed resources are equivalent in the `IsUpToDate` method of each resource's controller. The readability of this option is a little opaque in how it relates to Crossplane.

### How could Crossplane help solve your problem?

Perhaps we should add a function like our existing `EquateErrors` that equates managed resource parameters? This could just be an abstraction on `IgnoreInterfaces` to begin with.

**Comment by aditya109** [comment]
Hi @negz, is this issue still valid ?? If yes, I would like to work on this.

**Comment by negz** [comment]
I believe so! CC @muvaf who may have an opinion here.

**Comment by aditya109** [comment]
Thanks, pick this up then.

**Comment by muvaf** [comment]
Hi! I think `resource.AttributeReferencer` is remnant of the old approach we had taken back then. All reference-related functionality resides in `pkg/reference` package. In fact `pkg/resource/reference.go` can be deleted, @aditya109 this could be your first contribution 🙂

**Comment by aditya109** [comment]
Thanks @muvaf, will keep it in mind. Excited to try working on this repo.
