### ISSUE TITLE
OAM fieldPath should have leading dot 

### ISSUE THREAD

**Issue by wonderflow** [crossplane/crossplane-runtime#136]
### What problem are you facing?

> OAM fieldPaths are specified as JSON field paths with a leading dot, for example .spec.containers[0].image 

https://github.com/oam-dev/spec/blob/master/4.component.md#parameter

But in fieldPath library here, we can't add leading dot.

https://github.com/crossplane/crossplane-runtime/blob/master/pkg/fieldpath/fieldpath_test.go#L216

**Comment by negz** [comment]
https://github.com/kubernetes/community/blob/ddc11a7/contributors/devel/sig-architecture/api-conventions.md#selecting-fields

Kubernetes API convention is to omit the leading dot. We use this library for Kubernetes things as well as OAM things; I think it would be easier to update the OAM convention to omit the leading dot.

**Comment by wonderflow** [comment]
I agree, we just need align with OAM spec

**Comment by negz** [comment]
Seems like we'll change the OAM spec to reflect the library, rather than the other way around, so I'm going to close this issue.
