### ISSUE TITLE
Allow resource claims to be backed up and restored

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane-runtime#138]
### What problem are you facing?

When a managed resource and its resource claim are backed up and subsequently restored using a tool like https://velero.io they do not remain bound:

```
$ kubectl get mysqlinstances.database.crossplane.io -A
 NAMESPACE   NAME         STATUS   CLASS-KIND              CLASS-NAME                          RESOURCE-KIND      RESOURCE-NAME            AGE
 hasan       testme-sql            CloudSQLInstanceClass   hasan-cloudsqlinstanceclass-mysql   CloudSQLInstance   hasan-testme-sql-ngzkq   27m
 $ kubectl get CloudSQLInstance
 NAME                     STATUS    STATE      CLASS                               VERSION     AGE
 hasan-testme-sql-ngzkq   Unbound   RUNNABLE   hasan-cloudsqlinstanceclass-mysql   MYSQL_5_7   27m
```

### How could Crossplane help solve your problem?

It should be possible to backup a managed resource and its claim, then recreate them (in any order) and have them remain bound and functional.

**Comment by jbw976** [comment]
Might be worth poking in velero issues or slack to get some advice on how this should be handled.  not restoring owner references seems a bit broken to me too but i'm sure it's something they thought through and they may have insight to share on how to handle this as a consumer of velero.  This is the first issue i found on the topic, wonder if there are more: https://github.com/vmware-tanzu/velero/issues/965

**Comment by negz** [comment]
> not restoring owner references seems a bit broken to me too

@jbw976 I'm not sure I feel Velero's current behaviour is broken. I could see a case that we could be using controller references better.

Currently Crossplane relies on controller references to:

1. Provide a human readable (i.e. via `kubectl describe`) indication of a child->parent relationship.
1. Enable automatic garbage collection of orphaned children.
1. Avoid accidentally commandeering and overwriting resources that collide with desired children.

1 and 2 seem like uncontroversial uses for controller references based on my read of the [controller reference design document](https://github.com/kubernetes/community/blob/c529f24/contributors/design-proposals/api-machinery/controller-ref.md), but I'm not so sure about 3. 

In the third case we're using the controller reference to prevent the case in which:

1. A secret named `coolsecret` exists. It has nothing to do with Crossplane.
1. Someone creates a `MySQLInstance` with `spec.writeConnectionSecretToRef.name: coolsecret`. 
1. Crossplane overwrites `coolsecret` with the connection secret of the `MySQLInstance`.

It seems like controller references intend to prevent two parent resources fighting over one child resource, but don't necessarily intend to ensure that a parent will never adopt a child it did not create. In fact this is explicitly called out as something a parent resource may do.

> The main goal of ControllerRef (controller reference) is to solve the problem of controllers that fight over controlled objects due to overlapping selectors

> If a controller finds an orphaned object (an object with no ControllerRef) that matches its selector, it may try to adopt the object by adding a ControllerRef.

This isn't super clear cut, because the controller reference design doesn't really cover our use case. It appears to be assuming child resources are always matched by a label selector, and are somewhat fungible.

My suggestion is that for Crossplane connection secrets we:

1. Use a bespoke secret type, e.g. `type: connection.crossplane.io/v1alpha`, not `type: Opaque`.
1. Always set a controller reference when creating secrets.
1. Always adopt secrets of `type: connection.crossplane.io/v1alpha1`

This should:

* Prevent Crossplane accidentally (or being coerced into maliciously) overwriting existing secrets that have nothing to do with Crossplane.
* Allow resource claims and managed resources to re-adopt their connection secrets when backed up and restored.
* More clearly match the intent of the controller reference design, in that if two different resource claims wanted to write the same secret one would win and the other would lose.

**Comment by muvaf** [comment]
> Prevent Crossplane accidentally (or being coerced into maliciously) overwriting existing secrets that have nothing to do with Crossplane.

The different secret type suggestion solves this problem, or at least mitigates it, while we still miss the case where two Crossplane-created secrets having the same name/namespace at different times but for different resources. But I think that's a fair compromise.

On the other hand, Velero could actually have a logic for handling those like scan the owner references and renew the UID in them with the resources that are deployed during restore. Restoration would look like graph resolution of the owner references.

All that said, `type: connection.crossplane.io/v1alpha1` is a pretty good solution IMO.
