### ISSUE TITLE
Enable concurrent reconciliation of different CRs

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane-runtime#143]
### What problem are you facing?

Controller-runtime apparently runs only one go routine of `Reconcile` at a time and keeps other CR instances in the queue until the current one is finished. I always assumed that the reconciliations are separate go routines and independently run but it seems [it isn't the case](https://github.com/kubernetes-sigs/controller-runtime/blob/2361b0515224bcc1cd05d63503c6cf85b80cfd85/pkg/controller/controller.go#L35). I was wondering about why there is some sluggishness in getting to the final state when testing the template stacks and WP, this could be the cause.

### How could Crossplane help solve your problem?

I think we can enable this [concurrency option](https://github.com/kubernetes-sigs/controller-runtime/blob/2361b0515224bcc1cd05d63503c6cf85b80cfd85/pkg/controller/controller.go#L35) for most of our controllers, especially managed reconciler where the resources are completely independent. It's a simple option enabling(maybe make it 5 by default?) but we'd need to test it thoroughly. Possible problems to encounter:
* Increase in cpu usage at one time due to parallelization.
* Hitting API rate limits of cloud providers.

**Comment by jbw976** [comment]
@muvaf can you explain a little deeper on why we'd see slowdown for template stacks and wordpress when max concurrency is 1? I would hope that any given reconciliation attempt is pretty quick, e.g. it does not wait on long running operations that would prevent the reconciliation attempt from returning quickly.  Is there something about the design of template stacks rendering that would result in a blocked/long reconciliation attempt? It would be good to understand that better.

One hope here is that in order for concurrency greater than 1 to be "safe", reconcile events for a given resource should be de-duped or batched, so there is never 2 reconcile attempts working on the same resource at the same time.  I recall that controller-runtime does that de-dupe/batching, but that would be another thing to confirm during any testing of a concurrency greater than 1.

**Comment by muvaf** [comment]
OMG. I can swear I wrote two paragraph answer a few days ago. Really started to suspect Github is losing data.

> can you explain a little deeper on why we'd see slowdown for template stacks and wordpress when max concurrency is 1? I would hope that any given reconciliation attempt is pretty quick, e.g. it does not wait on long running operations that would prevent the reconciliation attempt from returning quickly. Is there something about the design of template stacks rendering that would result in a blocked/long reconciliation attempt? It would be good to understand that better.

Template stacks deploy bunch of resources referring each other. The sluggishness I see is about reference resolution. So, it's more about having deployed a bunch of resources with possibly deep tree of references, rather than something specific to template stacks. In other words, we'd be seeing the same behavior if we do `kubectl apply -f <folder>`.

I think there are two possible causes:
* When a referenced resource reaches `Ready` state, referencer does not get any event, so, it has to check in the first reconcile, which is configured as max 30 seconds in case no event hits. When the tree is large, possibility of this time to be on the longer side of the 30sec is higher in cases where referencing tree is deep rather than wide, i.e. resources serially refer each other.
* When there are N instances of the same kind, at any point in time only 1 instance is reconciled by the controller of that kind. So, if you deploy 10 AWS Subnet resources, the controller will put them in a FIFO queue even though the instances can be actually reconciled independently.

What the concurrency referred in this context aims to solve the second possible cause. When `MaxConcurrentReconciles` is 5 and 10 AWS Subnet resources need to be reconciled, it happens in 2 batches (5 go routines + 5 go routines) as oppposed to today (1 at a time).

> One hope here is that in order for concurrency greater than 1 to be "safe", reconcile events for a given resource should be de-duped or batched, so there is never 2 reconcile attempts working on the same resource at the same time. I recall that controller-runtime does that de-dupe/batching, but that would be another thing to confirm during any testing of a concurrency greater than 1.

Yes, this doesn't change. Controller-runtime always guarantees that no other reconcile attempts will be made for resource A until its current one finishes. This is more about a controller being able to process more than 1 different CR instances at the same time via different go routines.

**Comment by negz** [comment]
This isn't fully rolled out yet, but we put the plumbing in place in https://github.com/crossplane/crossplane-runtime/pull/294 and rolled it out to c/c at least.
