### ISSUE TITLE
Mock for resource.ClientApplicator

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane-runtime#178]
### What problem are you facing?

Currently, we're able to use fake.MockClient and its functions to mock the controller-runtime client. However, there is no mock ClientApplicator, which makes it hard to replace `Apply` with a function that returns given error.

### How could Crossplane help solve your problem?

Expand MockClient or implement a MockClientApplicator.

**Comment by negz** [comment]
iirc ClientApplicator is a struct that embeds the Client and Applicator interfaces, so I usually just write something like:


```go
ca := resource.ClientApplicator{
    Client: &test.MockClient{
        MockGetFn: func(...) error { return nil }
    },
    Applicator: resource.ApplyFn(func(...) error { return nil }),
}
```

Would a mock make this much easier? I imagine you'd end up needing about the same amount of typing to get it all setup.
