### ISSUE TITLE
Claim reconciler does not honor managed resource claimRef

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane-runtime#19]
### What happened?

Currently the resource claim reconciler supports two 'provisioning' options:

* Dynamic managed resource provisioning. If a resource claim sets its `.spec.classRef` and omits its `.spec.resourceRef` the reconciler will attempt to use the referenced class to create and bind to a new managed resource.
* Static managed resource provisioning. If a resource claim sets its `.spec.resourceRef` the reconciler will ignore any `.spec.classRef` and attempt to bind to the referenced managed resource.

All Crossplane managed resources expose a `.spec.claimRef` field, which is an object reference to the resource claim to which the manage resource either is bound, or (I assume) intends to be bound. During dynamic provisioning the claim reconciler sets this field to reference the managed resource it creates. During static provisioning it ignores it completely; if claim A references unbound resource B the claim reconciler will bind to it, even if _it_ references claim C.

It's not immediately obvious to me whether a managed resource author explicitly specifying the resource claim to which it should bind is a use case we want to support. If it's not we should move `.spec.claimRef` to `.status.claimRef`. If it is we should update the resource claim reconcile logic to avoid attempting to bind to managed resources that reference another claim. Either way, we should ensure the `claimRef` is set during the static provisioning scenario.

### How can we reproduce it?

1. Create managed resource A with a `claimRef` to resource claim B
1. Create resource claim C with a `resourceRef` to resource A

You should see claim C successfully bind to resource A, despite it referencing claim B.

### What environment did it happen in?
Crossplane version:

**Comment by negz** [comment]
CC @jbw976 @bassam can anyone shed light on why the `claimRef` field is in a managed resource's `.spec`, and not its `.status`? Are there scenarios in which we intend a Crossplane user to author a managed resource that explicitly references a resource claim, or is this field intended to be set only by Crossplane controllers?

I notice managed resources also expose `.spec.classRef`, which in the current codebase is completely informational - we'd ignore it if a user set it.

**Comment by jbw976** [comment]
I don't know of any scenarios where we'd expect the user to set a managed resource's `.spec.claimRef`, it seems like something only controllers would set. I'm not remember any reason from the past on why it was put into `.spec`, perhaps that wasn't intentional.

**Comment by negz** [comment]
I'm going to close this given that we plan to deprecate claims and classes.
