### ISSUE TITLE
APIUpdatingApplicator behavior is unexpected

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane-runtime#191]
### What happened?

`NewAPIUpdatingApplicator` moved from broken (see https://github.com/crossplane/crossplane-runtime/issues/165) to just having unexpected behavior in https://github.com/crossplane/crossplane-runtime/pull/176. The original proposal in that PR was to fix the problem by always forcing the resource version of the `desired` to match that of the `current` before calling `Update`. This would mean that whatever was in `desired` would overwrite what was `current`. There was rightful [concern](https://github.com/crossplane/crossplane-runtime/pull/176#discussion_r422405453) about doing this in the primary place this was being used (`KubernetesApplication`), but that case is not reflective of the typical desired use of `Update` (which is to overwrite what is existing).

In fact, one of the places where we are currently using the `APIUpdatingApplicator`, propagating the managed connection secret to the claim connection secret, is not functioning as expected. Because the `APIUpdatingApplicator` updates with `current` **those connection secrets actually never get updated**. This was [called out in the PR](https://github.com/crossplane/crossplane-runtime/pull/176#discussion_r422429911), but appears to have been lost among the discussion. 

You _can_ force the overwrite by just setting `current` to `desired` in an `UpdateFn`, but it requires you to know the underlying type of the object you are dealing with. More on this below.

### How can we reproduce it?

I was using the `APIUpdatingApplicator` to create and update objects installed by the new package manager. This is a case where we want an existing object to be completely overwritten by the new. This works fine as long as we know exactly what types we are dealing with. For example:
```go
if err := r.client.Applicator.Apply(ctx, res, resource.MustBeControllableBy(pr.GetUID()), resource.UpdateFn(func(current, desired runtime.Object) {
	c := current.(*apiextensionsv1alpha1.CompositeResourceDefinition)
	d := desired.(*apiextensionsv1alpha1.CompositeResourceDefinition)
	// Make desired owner references match current.
	d.SetOwnerReferences(c.GetOwnerReferences())

	// Applicator will have already checked that this resource is
	// controllable, so it is safe for us to apply a controller
	// reference.
	_ = meta.AddControllerReference(d, meta.AsController(meta.ReferenceTo(pr, pr.GetObjectKind().GroupVersionKind())))

	// Make desired resource version match current.
	d.SetResourceVersion(c.GetResourceVersion())

	// Set current to match desired.
	*c = *d
})); err != nil {
	log.Debug("cannot create XRD for package revision", "error", err)
	pr.SetConditions(runtimev1alpha1.Unavailable(), runtimev1alpha1.ReconcileSuccess())
	return reconcile.Result{RequeueAfter: shortWait}, errors.Wrap(r.client.Status().Update(ctx, pr), errUpdateStatus)
}
```
Will correctly update the object with the new schema because we are manipulating the underlying value of the `current` ptr. However, if we want to deal generally with any object type, for example:
```go
if err := r.client.Applicator.Apply(ctx, res, resource.MustBeControllableBy(pr.GetUID()), resource.UpdateFn(func(current, desired runtime.Object) {
	c := current.(resource.Object)
	d := desired.(resource.Object)

	// Make desired owner references match current.
	d.SetOwnerReferences(c.GetOwnerReferences())

	// Applicator will have already checked that this resource is
	// controllable, so it is safe for us to apply a controller
	// reference.
	_ = meta.AddControllerReference(d, meta.AsController(meta.ReferenceTo(pr, pr.GetObjectKind().GroupVersionKind())))

	// Make desired resource version match current.
	d.SetResourceVersion(c.GetResourceVersion())

	// Set current to match desired.
	c = d
})); err != nil {
	log.Debug("cannot create CRD for package revision", "error", err)
	pr.SetConditions(runtimev1alpha1.Unavailable(), runtimev1alpha1.ReconcileSuccess())
	return reconcile.Result{RequeueAfter: shortWait}, errors.Wrap(r.client.Status().Update(ctx, pr), errUpdateStatus)
}
```
It will not work because we are not changing the underlying value of `current`.

### Proposed Fix

I think it would be a better experience to revert back to updating with the passed in object, and setting the correct resource version automatically. This would mean that the default behavior would be to overwrite the existing with whatever the desired was, and users could manipulate that desired object in the `ApplyOptions`. This is what the updated function would look like:
```go
// Apply changes to the supplied object. The object will be created if it does
// not exist, or updated if it does.
func (a *APIUpdatingApplicator) Apply(ctx context.Context, o runtime.Object, ao ...ApplyOption) error {
	m, ok := o.(metav1.Object)
	if !ok {
		return errors.New("cannot access object metadata")
	}

	if m.GetName() == "" && m.GetGenerateName() != "" {
		return errors.Wrap(a.client.Create(ctx, o), "cannot create object")
	}

	current := o.DeepCopyObject()

	err := a.client.Get(ctx, types.NamespacedName{Name: m.GetName(), Namespace: m.GetNamespace()}, current)
	if kerrors.IsNotFound(err) {
		// TODO(negz): Apply ApplyOptions here too?
		return errors.Wrap(a.client.Create(ctx, o), "cannot create object")
	}
	if err != nil {
		return errors.Wrap(err, "cannot get object")
	}

	for _, fn := range ao {
		if err := fn(ctx, current, o); err != nil {
			return err
		}
	}

	// Always set the resource version of the desired to match existing.
	o.(metav1.Object).SetResourceVersion(current.(metav1.Object).GetResourceVersion())
	return errors.Wrap(a.client.Update(ctx, o), "cannot update object")
}
```

This would support a case like the following where the consumer desires to update an object, but persist the existing owner references:
```go
if err := r.client.Applicator.Apply(ctx, res, resource.MustBeControllableBy(pr.GetUID()), resource.UpdateFn(func(current, desired runtime.Object) {
	c := current.(resource.Object)
	d := desired.(resource.Object)

	// Make desired owner references match current.
	d.SetOwnerReferences(c.GetOwnerReferences())

	// Applicator will have already checked that this resource is
	// controllable, so it is safe for us to apply a controller
	// reference.
	_ = meta.AddControllerReference(d, meta.AsController(meta.ReferenceTo(pr, pr.GetObjectKind().GroupVersionKind())))
})); err != nil {
	log.Debug("cannot create object for package revision", "error", err)
	pr.SetConditions(runtimev1alpha1.Unavailable(), runtimev1alpha1.ReconcileSuccess())
	return reconcile.Result{RequeueAfter: shortWait}, errors.Wrap(r.client.Status().Update(ctx, pr), errUpdateStatus)
}
```

**Comment by negz** [comment]
Thanks for writing this up @hasheddan! This function has a complicated history - I kind of regret introducing it given how buggy and hard to grok it has been. That said, given we're using it in a handful of places I agree we should fix it.

> In fact, one of the places where we are currently using the APIUpdatingApplicator, propagating the managed connection secret to the claim connection secret, is not functioning as expected. Because the APIUpdatingApplicator updates with current those connection secrets actually never get updated. 

It seems like `APIUpdatingApplicator` is working "as expected", but "as expected" isn't particularly intuitive, and we didn't update the [calling code](https://github.com/crossplane/crossplane-runtime/blob/1576699ee9ac5af89359795a459a27583512ad50/pkg/resource/api.go#L106) in `APIConnectionPropagator` to reflect the new behaviour, in which the update is a no-op unless you pass an `UpdateFn`? So we could probably fix `APIConnectionPropagator` by passing in an `UpdateFn` that updated the resource claim secret, since we can type assert the `runtime.Object` to a `*Secret`.

However, in the case where we don't know exactly what is in a `runtime.Object` interface there's no way to simply completely overwrite the current `runtime.Object`, because we pass the `runtime.Object` interfaces to `UpdateFn` by value. One option would be to pass pointers to `runtime.Object` to `UpdateFn` - e.g. https://play.golang.org/p/WyrS2Nkdvwt.

I don't have strong feelings either way as to whether we keep requiring an `UpdateFn`, but update it to take pointer arguments, or whether we overwrite the resource version, thus making the `UpdateFn` optional.

**Comment by hasheddan** [comment]
I think I would prefer to update automatically, as pointers to interfaces are not super common in go and can be confusing to work with. I also think that it is more in-line with what I would think an `APIUpdatingApplicator` would do based on the name.
