### ISSUE TITLE
Setting or Getting a field of Paved object with "."

### ISSUE THREAD

**Issue by allenhaozi** [crossplane/crossplane-runtime#239]
if I want to get or set gpu resource `spec.template.spec.containers[0].resources.limits.nvidia.com/gpu`

Is there a good way to solve this situation ?

**Comment by negz** [comment]
@allenhaozi I believe so - you should be able to use square brackets, for example:

`spec.template.spec.containers[0].resources.limits[nvidia.com/gpu]`

Let us know if that doesn't work.
