### ISSUE TITLE
Crossplane should refuse to operate on existing external resources

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane-runtime#27]
### What problem are you facing?

As more and more Crossplane managed resources support updating (in addition to creating and deleting) their external resources, we're likely to run into cases where Crossplane will "implicitly adopt" and start managing existing external resources. This will become more prevalent as more Crossplane managed resources allow configuration of their underlying external resource names per https://github.com/crossplaneio/crossplane/issues/624.

For example, assume a critical 1TB CloudSQL database named `prod` exists in a particular GCP account. Further assume Crossplane is configured to use this GCP account, and a resource claim for a 10GB CloudSQL database with external name `prod` was created. Today there is no logic that would prevent Crossplane considering the existing database to be under Crossplane management, and trying to resize it down to 10GB.

### How could Crossplane help solve your problem?

Crossplane will need to be able to distinguish external resources it created from existing external resources. This may be difficult, given that not all cloud providers and external resources support storing metadata.

Relates to crossplaneio/crossplane-runtime#22.

**Comment by negz** [comment]
I'm less convinced we need to be concerned about this - at least until we get some data from users that it's a problem. For now I'm going to close this issue.

**Comment by ugurcancaykara** [comment]
Hi, can I get an update about this ? 
Use case scenario:
- Provisioned two DynamoDB table (Table resource) in two aws region
- Provisioned a DynamoDB GlobalTable for them
I was planning to configure autoscaling when it comes PROVISIONED billing mode however it's not currently supported.
Since crossplane recovers the changes I make manually that's not an option but a solution like this would be helpful. I would provision these resources as code and put the update: Observe policy to manifest file and I could handle the rest manually.

**Comment by metrictwo** [comment]
+1 for an update, please. This feature is table-stakes given the risk of accidentally modifying existing production resources.

**Comment by jeanduplessis** [comment]
@ugurcancaykara @metrictwo would either of these solutions work for you:
https://github.com/crossplane/crossplane/pull/3531/files
https://github.com/crossplane/crossplane/pull/3822/files

**Comment by metrictwo** [comment]
@jeanduplessis Thanks for the response. Neither of those quite work for our use case. What we'd ideally like is a way to configure crossplane such that when a crossplane resource is created that represents an existing infra resource, it will import fields, but refuse to reconcile the resource altogether until/unless it's been indicated by some field or annotation that it's okay to do so. We want crossplane to be free to manage resources that it created, though.

**Comment by bobh66** [comment]
> What we'd ideally like is a way to configure crossplane such that when a crossplane resource is created that represents an existing infra resource, it will import fields, but refuse to reconcile the resource altogether until/unless it's been indicated by some field or annotation that it's okay to do so.

That sounds like the definition of `managementPolicy : ObserveOnly` in https://github.com/crossplane/crossplane/pull/3822/files

**Comment by metrictwo** [comment]
@bobh66 It's close, but that only helps when we're intentionally importing an existing infra resource, whereas our concern is about the case of accidentally importing one (or rather, any unintended modifications that may follow). Basically we'd love to have terraform's behavior of not manipulating anything that hasn't been explicitly imported.
