### ISSUE TITLE
Add event in resource on observe out of sync with diff in message

### ISSUE THREAD

**Issue by vaspahomov** [crossplane/crossplane-runtime#274]
### What problem are you facing?
Like verbose logging was added in #271. Also add diff message in resource events.

### How could Crossplane help solve your problem?
More easy to debug resources via `kubectl describe` without reading logs. 
Common users of provider can do `kubectl describe` to found problem, when read logs can only provider admins.

**Comment by negz** [comment]
I think I like this idea from a debuggability standpoint, but I'm not sure how diffs would be rendered in `kubectl describe` output. We also might need to consider the increased size of the event payload if we start including diffs.

**Comment by vaspahomov** [comment]
@negz I've create PR #275 
There are some examples of kubectl describe output

**Comment by negz** [comment]
I appreciate you opening the PR. This is a tough one, but after discussion at the last community meeting the consensus among the maintainers is that we'd prefer to keep this at the debug logging level for now, so I am going to close this. We do appreciate the suggestion though, and the discussion it spurred around the trickiness of IsUpToDate.
