### ISSUE TITLE
External name of CR doesn't get updated in reconciler

### ISSUE THREAD

**Issue by shu-ming** [crossplane/crossplane-runtime#330]
### What happened?
I am writing a custom crossplane provider. In the Create function, I set the CR with the instance ID that returns from external call. Then r.client.Update(ctx, managed) is called in the reconciler function. But the CR's annotation doesn't get changed to the new value. I got this problem by setting a breakpoint and running  step by step. I observed that external name in annotation would be updated finally. But it was not updated at the first hit. 

![image](https://user-images.githubusercontent.com/24264618/164463281-d6f7437d-10d2-447c-ba35-6da4322e26ea.png)

<img width="715" alt="image" src="https://user-images.githubusercontent.com/24264618/164463323-ea3eec94-2be9-4ef6-8cf7-2e2c6d5b26be.png">

```
func (e *external) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {
.......................
	instance, err := e.client.CreateInstance(req)
	if err != nil {
		e.log.Info("cr name: ", cr.Name, "create error", err)
		return managed.ExternalCreation{}, errors.Wrap(err, errCreateFailed)
	}

	meta.SetExternalName(cr, instance.ID)

	// Return connection details, that will extend later once more info is available
	return managed.ExternalCreation{
		ExternalNameAssigned: true,
		ConnectionDetails:    getConnectionDetails(cr.Spec.ForProvider.RootUsername, "", instance),
	}, nil
}
```
```
// crossplane-runtime@v0.12.0/pkg/reconciler/managed/reconciler.go
		if creation.ExternalNameAssigned {
			en := meta.GetExternalName(managed)
			// We will retry in all cases where the error comes from the api-server.
			// At one point, context deadline will be exceeded and we'll get out
			// of the loop. In that case, we warn the user that the external resource
			// might be leaked.
			err := retry.OnError(retry.DefaultRetry, resource.IsAPIError, func() error {
				nn := types.NamespacedName{Name: managed.GetName()}
				if err := r.client.Get(ctx, nn, managed); err != nil {
					return err
				}
				meta.SetExternalName(managed, en)
				return r.client.Update(ctx, managed)
			})
		}
```

### How can we reproduce it?

1. Run a crossplane provider with debug mode
2. Create a CR in cluster
3. Set a breakpoint at reconciler -if creation.ExternalNameAssigned 
4. Observe the external name

### What environment did it happen in?
Crossplane version: crossplane-runtime@v0.12.0

**Comment by muvaf** [comment]
Hmm it should've worked but we moved to a new [logic](https://github.com/crossplane/crossplane-runtime/blob/86fb15d/pkg/reconciler/managed/reconciler.go#L933) already that will always update the annotations. So, you might want to update the crossplane-runtime to see if that works for you. Feel free to reopen if it still doesn't work for you.
