### ISSUE TITLE
UpdateCriticalAnnotations does not support Namespace scope mange resources

### ISSUE THREAD

**Issue by raz-bn** [crossplane/crossplane-runtime#346]
### What happened?

When creating a managed resource in namespace scope instead of the default cluster scope, I'm facing lots of issues regarding cross-plane annotations. After some investigation, I noticed that the function [UpdateCriticalAnnotations](https://github.com/crossplane/crossplane-runtime/blob/d9c25ae277042c2ca2885fac24f74aec97349bc5/pkg/reconciler/managed/api.go#L194) does not support working with a managed resource who lives inside a namespace, this can be fixed easily by adding 
`namespace: o.GetNamespace()` to the NamespacedName struct. This would not break cluster-wide resources since it will use `""` for them

**Comment by negz** [comment]
Per #347 this is intentional.
