### ISSUE TITLE
resource references only support string fields

### ISSUE THREAD

**Issue by eljohnson92** [crossplane/crossplane-runtime#366]
### What happened?
Some terraform providers, such as the [Linode](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance) provider use resource IDs that are not strings and are instead of type [int](https://github.com/linode/terraform-provider-linode/blob/dev/linode/instance/schema_resource.go). This causes an issue when trying to create references between resources because the [FromPtrValue](https://github.com/crossplane/crossplane-runtime/blob/master/pkg/reference/reference.go#L46-L51) and [ToPtrValue](https://github.com/crossplane/crossplane-runtime/blob/master/pkg/reference/reference.go#L54-L59) only support strings for references. 

### How can we reproduce it?
I have reproduced this issue in this repository where you can see the issue [here](https://github.com/eljohnson92/provider-linode/blob/incorrect_machine_id/apis/instance/v1alpha1/zz_generated.resolvers.go#L41). it is possible to overwrite the terraform schema for parts of the codebase to be a string instead of an int, but it does cause some problems when reconciling external resources so if it were possible for these functions to just support int/float references as well as strings. 

I am happy to try and contribute a fix to have ToPtrValue and ForPtrValue support more types if that is what is needed but please let me know if I might be missing something or if there is a more appropriate place to fix this issue.

### What environment did it happen in?

crossplane version: [v0.19.0-rc.0](https://github.com/crossplane/crossplane-runtime/releases/tag/v0.19.0-rc.0)
upjet version: [v0.7.0](https://github.com/upbound/upjet/releases/tag/v0.7.0)

**Comment by negz** [comment]
Cross referencing https://github.com/crossplane/crossplane/issues/1770 - something to consider with that impending design.
