### ISSUE TITLE
Mutation on the cached object causes " fatal error: concurrent map iteration and map write"

### ISSUE THREAD

**Issue by Technovation22** [crossplane/crossplane-runtime#593]
### What happened?
Recently we noticed an error in the process of reconciling in provider-aws indicating that there is a race condition in accessing a map:
```
2023-10-16T03:29:57Z    2023-10-16T03:29:57.143Z    DEBUG    events    cannot get cache cluster list: api error Throttling: Rate exceeded    {"type": "Warning", "object": {"kind":"ReplicationGroup","name":"r-acf54be9-dc8c-445d-a712-1507bfd0660b-krb4x-gg48h","uid":"a0489de6-3fb1-4690-b248-12c482a3c175","apiVersion":"cache.aws.crossplane.io/v1beta1","resourceVersion":"647156184"}, "reason": "CannotObserveExternalResource"}
2023-10-16T03:29:57Z    2023-10-16T03:29:57.151Z    DEBUG    provider-aws    Reconciling    {"controller": "managed/replicationgroup.cache.aws.crossplane.io", "request": {"name":"r-acf54be9-dc8c-445d-a712-1507bfd0660b-krb4x-gg48h"}}
2023-10-16T03:29:57Z    fatal error: concurrent map iteration and map write
```
Then we traced it down and used a race detector and noticed mutation on the cached object might be causing this, the function  [Update()](https://github.com/crossplane/crossplane-runtime/blob/11ba5f5ef617cbd167c7e4a63993f9c2cef73f7d/pkg/resource/predicates.go#L87) seems to be updating the annotations and it can be happening at the same time provider-aws in another thread is reading from the cache and deep-copying the data.

```
Write at 0x00c001a153b0 by goroutine 2529:
  runtime.mapassign_faststr()
      /opt/homebrew/opt/go/libexec/src/runtime/map_faststr.go:203 +0x40c
  github.com/crossplane/crossplane-runtime/pkg/resource.AnnotationChangedPredicate.Update()
```

```
Previous read at 0x00c001a153b0 by goroutine 2740:
  k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).DeepCopyInto()
```

```
Goroutine 2529 (running) created at:
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start()
      /Users/i*****/golang/pkg/mod/k8s.io/apimachinery@v0.27.3/pkg/util/wait/wait.go:70 +0xd4
  k8s.io/client-go/tools/cache.(*sharedProcessor).addListener()
      /Users/i*****/golang/pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/shared_informer.go:743 +0x190
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).AddEventHandlerWithResyncPeriod()
      /Users/i*****/golang/pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/shared_informer.go:618 +0x534
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).AddEventHandler()
      /Users/i*****/golang/pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/shared_informer.go:556 +0x4c
  sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1()
      /Users/i*****/golang/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/source/kind.go:82 +0x438

Goroutine 2740 (running) created at:
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2()
      /Users/i*****/golang/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222 +0x5c0
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start()
      /Users/i*****/golang/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:233 +0x23c
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1()
      /Users/i*****/golang/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:219 +0x158
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func2()
      /Users/i*****/golang/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:222 +0x44
```

### How can we reproduce it?
We noticed this after some throttling conditions, not sure related but can be considered this race condition showed up after many requests to read/update resources.

### What environment did it happen in?
* Crossplane version: 1.13.2
* Cloud provider: AWS
* Provider-aws: v0.43.0
* Kubernetes version v1.25.10
* Os: Unavailable at this time
* Kernel: Unavailable at this time

I also found this [issue](https://github.com/kubernetes-sigs/controller-runtime/issues/2391) in controller-runtime. I attached the full result of the race detector to this issue.

[race.txt](https://github.com/crossplane/crossplane-runtime/files/13232949/race.txt)

**Comment by turkenh** [comment]
Thanks for reporting @Technovation22.

This issue looks quite similar to https://github.com/crossplane/crossplane-runtime/issues/560, which was expected to be solved with https://github.com/crossplane/crossplane-runtime/pull/561.

When I check `provider-aws: v0.43.0`, I notice that fix is already included, and the [Update](https://github.com/crossplane/crossplane-runtime/blob/11ba5f5ef617cbd167c7e4a63993f9c2cef73f7d/pkg/resource/predicates.go#L87) call should no longer mutate the cached object. 

So, could you please double-check the version of provider-aws and let us know while we investigate this further?

**Comment by turkenh** [comment]
Checking the attached trace logs and it indicates that it is using `/crossplane/crossplane-runtime@v0.20.0` 

```
WARNING: DATA RACE
Write at 0x00c001a153b0 by goroutine 2529:
  runtime.mapassign_faststr()
      /opt/homebrew/opt/go/libexec/src/runtime/map_faststr.go:203 +0x40c
  github.com/crossplane/crossplane-runtime/pkg/resource.AnnotationChangedPredicate.Update()
      /Users/i*****/golang/pkg/mod/github.com/crossplane/crossplane-runtime@v0.20.0/pkg/resource/predicates.go:213 +0x134
```

This proves that this happens with an old provider-aws version with crossplane-runtime v0.20.0 dependency. The latest seems to be [v0.40.0](https://github.com/upbound/provider-aws/blob/0f0d7a43d9d3b4919fb0f708f3a4794081dfbdd8/go.mod#L12). 

So, I would propose closing this as duplicate/fixed once you can confirm the provider-aws version.

**Comment by Technovation22** [comment]
Hi @turkenh 
Thanks for looking into this, we are not using upbound, I checked the version we are using in crossplane-contrib/provider-aws is [v0.43.0](https://github.com/crossplane-contrib/provider-aws/blob/release-0.43/go.mod). I see the crossplane-runtime upgrade from `v0.20.0` to `v1.13.0` was [committed](https://github.com/crossplane-contrib/provider-aws/commit/dca644be4fe37de54902e789f6fe30afcc3d6532) last week, maybe we need to wait for a new release to update.
