### ISSUE TITLE
Deprecate the reference pointer helper functions

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane-runtime#762]
From @negz comment in: https://github.com/crossplane/crossplane-runtime/pull/754#discussion_r1710367975, copied here for convenience:

> Huh, I actually forgot we had these pointer helpers in runtime.
>
> We usually use https://pkg.go.dev/k8s.io/utils/ptr instead these days. I'd suggest that. We should probably deprecate the ones we have in runtime, but that can happen in a separate PR.

Source location: https://github.com/crossplane/crossplane-runtime/blob/master/pkg/reference/reference.go

**Comment by jan-di** [comment]
Hi @jbw976/@negz, while upgrading to Upjet 1.5.0 we noticed that this change seems to be a breaking change:

Upjet 1.5 still uses the helper functions to generate the code for cross resource references. Therefore we need to stay on xp runtime 1.17 to keep it working.
