### ISSUE TITLE
Claim cannot be deleted if managed resource is already gone

### ISSUE THREAD

**Issue by muvaf** [crossplane/crossplane-runtime#81]
### What happened?

If claim reconciler cannot find the managed resource, it just requeues even though the user requested the claim to be deleted.

### How can we reproduce it?

- Create a claim.
- Wait for managed resource to be created.
- Delete the managed resource.
- Try deleting the claim. It won't go because of that https://github.com/crossplaneio/crossplane-runtime/blob/master/pkg/resource/claim_binding_reconciler.go#L314

### What environment did it happen in?
Crossplane-runtime version: 0.2.2

**Comment by hasheddan** [comment]
@muvaf could this be fixed by:

1. Setting the binding phase of the claim to `Unbound` when the managed resource is created.
1. Before checking if the managed resource exists in the claim binding reconciler:

```go
if meta.WasDeleted(claim) && claim.GetBindingPhase() == v1alpha1.BindingPhaseUnbound {
	if err := r.claim.RemoveFinalizer(ctx, claim); err != nil {
		// If we didn't hit this error last time we'll be requeued
		// implicitly due to the status update. Otherwise we want to retry
		// after a brief wait, in case this was a transient error.
		claim.SetConditions(v1alpha1.Deleting(), v1alpha1.ReconcileError(err))
		return reconcile.Result{RequeueAfter: aShortWait}, errors.Wrap(r.client.Status().Update(ctx, claim), errUpdateClaimStatus)
	}

	// We've successfully deleted our claim and removed our finalizer. If we
	// assume we were the only controller that added a finalizer to this
	// claim then it should no longer exist and thus there is no point
	// trying to update its status.
	return reconcile.Result{Requeue: false}, nil
}
```

**Comment by negz** [comment]
We're not going to fix this since we're deprecating resource claims. That said, we may need to raise an issue to make sure requirements do not face the same problem given how similar their implementation is to claims.
